import subprocess
import os
import glob
import re 
import json # <-- Added this import!

# Traverse up from manager/tools/ to the project root where the scripts live
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "scripts"))

def run_transform_script() -> dict:
    """Executes 1-transform_kvms.py and parses the log for exact metrics."""
    print("--- Tool: run_transform_script called ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "kvm-migration-scripts", "1-transform_kvms.py")
        
        # Execute the script in the project root directory
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        
        if result.returncode != 0:
            return {"status": "error", "message": "Script failed to execute properly."}
            
        # Locate the log file generated by your script's Tee class
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "transform_kvms_run")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        
        if not list_of_files:
            return {"status": "success", "message": "Script ran, but no log file was generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_lines = f.readlines()
            
        # Extract facts to return to the agent
        success_count = sum(1 for line in log_lines if "[SUCCESS]" in line)
        error_count = sum(1 for line in log_lines if "❌ ERROR" in line or "❌ Error" in line)
        warning_count = sum(1 for line in log_lines if "⚠️ WARNING" in line)
        
        return {
            "status": "success", 
            "metrics": {
                "successfully_transformed": success_count,
                "errors_encountered": error_count,
                "warnings": warning_count
            }
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}
    
def run_import_script() -> dict:
    """Executes 2-import_kvm.py synchronously, blocks until finished, and extracts stats."""
    print("--- Tool: run_import_script called ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "kvm-migration-scripts", "2-import_kvm.py")
        
        # This blocks the agent until the script completely finishes
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "import_kvms_run")
        if not os.path.exists(log_dir):
             return {"status": "error", "message": "Log directory not found."}

        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        if not list_of_files:
            return {"status": "error", "message": "Script ran but no log file was generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_content = f.read()
            
        def extract_stat(label):
            match = re.search(rf"{label}\s*:\s*(\d+)", log_content)
            return int(match.group(1)) if match else 0

        stats = {
            "files_processed": extract_stat("Files Processed"),
            "maps_created": extract_stat("Maps Created"),
            "maps_synced": extract_stat("Maps Synced"),
            "entries_created": extract_stat("Entries Created"),
            "entries_updated": extract_stat("Entries Updated"),
            "files_deleted": extract_stat("Files Deleted"),
            "failures": extract_stat("Failures")
        }

        # Check for any failures or a non-zero exit code
        if result.returncode != 0 or stats["failures"] > 0:
            error_lines = [line.strip() for line in log_content.split('\n') if '❌' in line or 'Error:' in line]
            unique_errors = list(dict.fromkeys(error_lines))
            return {
                "status": "completed_with_errors", 
                "summary_data": stats,
                "error_details": unique_errors[:5]
            }

        return {"status": "completed_successfully", "summary_data": stats}
        
    except Exception as e:
        return {"status": "error", "message": str(e)}
    
def run_surgical_delete_script(target_org: str, target_scope: str, target_kvm: str) -> dict:
    """
    Runs the registry-based deletion script.
    target_scope: 'all', 'org', 'all_envs', or specific env name.
    target_kvm: 'all', or specific kvm name.
    """
    print(f"--- Tool: run_surgical_delete_script called ({target_org}, {target_scope}, {target_kvm}) ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "kvm-migration-scripts", "3-delete_registry_kvms.py")
        
        # Execute script from project root
        result = subprocess.run([
            "python", script_path, 
            "--org", target_org, 
            "--scope", target_scope, 
            "--kvm", target_kvm
        ], cwd=PROJECT_ROOT)
        
        if result.returncode != 0:
            return {"status": "error", "message": "Deletion script failed."}
            
        # Locate the new log file
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "delete_kvms_run")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        
        if not list_of_files:
            return {"status": "success", "message": "Script ran, but log was missing."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_lines = f.readlines()
            
        # Extract metrics
        deleted = sum(1 for line in log_lines if "[SUCCESS]" in line)
        failed = sum(1 for line in log_lines if "[FAILURE]" in line)
        
        return {
            "status": "success", 
            "metrics": {
                "deleted": deleted,
                "failed": failed
            }
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}
    
def run_view_all_kvms_script() -> dict:
    """Executes the validation script and returns the live data directly to the agent."""
    print("--- Tool: run_view_all_kvms_script called ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "kvm-migration-scripts", "4-validate_kvms.py")
        
        # Capture the standard output (stdout) where the script prints the JSON
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT, capture_output=True, text=True)
        
        if result.returncode == 0:
            # Instead of looking for a file, we parse the JSON printed by the script
            # (We will update the script to print the final JSON to stdout)
            try:
                # Find the start of the JSON block in the output
                output = result.stdout
                json_start = output.find('{')
                json_data = json.loads(output[json_start:])
                return {"status": "success", "data": json_data}
            except:
                return {"status": "error", "message": "Failed to parse script output."}
        else:
            return {"status": "error", "message": result.stderr}
            
    except Exception as e:
        return {"status": "error", "message": str(e)}
    

def run_transform_developer_script() -> dict:
    """Executes 1-transform_developers.py and extracts the list of names."""
    print("--- Tool: run_transform_developer_script called ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "developer-migration-scripts", "1-transform_developers.py")
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        
        if result.returncode != 0:
            return {"status": "error", "message": "Script failed."}
            
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "transform_developers_run")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        if not list_of_files:
            return {"status": "success", "message": "No log generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_lines = f.readlines()
            
        # Parse names for the client-facing UI
        success_names = [line.split(": ")[1].strip() for line in log_lines if "[SUCCESS]" in line]
        failure_names = [line.split(": ")[1].strip() for line in log_lines if "[FAILURE]" in line]
        
        return {
            "status": "success", 
            "metrics": {
                "total_success": len(success_names),
                "total_failed": len(failure_names)
            },
            "transformed_developers": success_names,
            "failed_developers": failure_names
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}
    
def run_import_developer_script() -> dict:
    """Executes 2-import_developers.py and returns metrics."""
    try:
        script_path = os.path.join(PROJECT_ROOT, "developer-migration-scripts", "2-import_developers.py")
        subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "import_developers_run")
        latest_file = max(glob.glob(os.path.join(log_dir, "*.log")), key=os.path.getctime)
        with open(latest_file, 'r') as f: lines = f.readlines()
        
        successes = [l.split(": ")[1].strip() for l in lines if "[SUCCESS]" in l]
        return {"status": "success", "metrics": {"imported": len(successes)}, "imported_names": successes}
    except Exception as e: return {"status": "error", "message": str(e)}

def run_delete_developer_script() -> dict:
    """Executes 3-delete_developers.py and returns metrics."""
    try:
        script_path = os.path.join(PROJECT_ROOT, "developer-migration-scripts", "3-delete_developers.py")
        subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "delete_developers_run")
        latest_file = max(glob.glob(os.path.join(log_dir, "*.log")), key=os.path.getctime)
        with open(latest_file, 'r') as f: lines = f.readlines()
        
        deleted = [l.split(": ")[1].strip() for l in lines if "[SUCCESS]" in l]
        return {"status": "success", "metrics": {"deleted": len(deleted)}, "deleted_names": deleted}
    except Exception as e: return {"status": "error", "message": str(e)}
