import subprocess
import os
import glob
import re 
import json
import sys # <-- Added this import!

# Traverse up from manager/tools/ to manager/ where the scripts live
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "scripts"))

def run_transform_script() -> dict:
    """Executes 1-transform_kvms.py and parses the log for exact metrics."""
    print("--- Tool: run_transform_script called ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "kvm-migration-scripts", "1-transform_kvms.py")
        
        # Execute the script in the project root directory
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        
        if result.returncode != 0:
            return {"status": "error", "message": "Script failed to execute properly."}
            
        # Locate the log file generated by your script's Tee class
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "transform_kvms_run")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        
        if not list_of_files:
            return {"status": "success", "message": "Script ran, but no log file was generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_lines = f.readlines()
            
        # Extract facts to return to the agent
        success_count = sum(1 for line in log_lines if "[SUCCESS]" in line)
        error_count = sum(1 for line in log_lines if "❌ ERROR" in line or "❌ Error" in line)
        warning_count = sum(1 for line in log_lines if "⚠️ WARNING" in line)
        
        return {
            "status": "success", 
            "metrics": {
                "successfully_transformed": success_count,
                "errors_encountered": error_count,
                "warnings": warning_count
            }
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}
    
def run_import_script_bkp() -> dict:
    """Executes 2-import_kvm.py synchronously, blocks until finished, and extracts stats."""
    print("--- Tool: run_import_script_bkp called ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "kvm-migration-scripts", "2-import_kvm.py")
        
        # This blocks the agent until the script completely finishes
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "import_kvms_run")
        if not os.path.exists(log_dir):
             return {"status": "error", "message": "Log directory not found."}

        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        if not list_of_files:
            return {"status": "error", "message": "Script ran but no log file was generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_content = f.read()
            
        def extract_stat(label):
            match = re.search(rf"{label}\s*:\s*(\d+)", log_content)
            return int(match.group(1)) if match else 0

        stats = {
            "files_processed": extract_stat("Files Processed"),
            "maps_created": extract_stat("Maps Created"),
            "maps_synced": extract_stat("Maps Synced"),
            "entries_created": extract_stat("Entries Created"),
            "entries_updated": extract_stat("Entries Updated"),
            "files_deleted": extract_stat("Files Deleted"),
            "failures": extract_stat("Failures")
        }

        # Check for any failures or a non-zero exit code
        if result.returncode != 0 or stats["failures"] > 0:
            error_lines = [line.strip() for line in log_content.split('\n') if '❌' in line or 'Error:' in line]
            unique_errors = list(dict.fromkeys(error_lines))
            return {
                "status": "completed_with_errors", 
                "summary_data": stats,
                "error_details": unique_errors[:5]
            }

        return {"status": "completed_successfully", "summary_data": stats}
        
    except Exception as e:
        return {"status": "error", "message": str(e)}
    
def run_surgical_delete_script(target_org: str, target_scope: str, target_kvm: str) -> dict:
    """
    Runs the registry-based deletion script.
    target_scope: 'all', 'org', 'all_envs', or specific env name.
    target_kvm: 'all', or specific kvm name.
    """
    print(f"--- Tool: run_surgical_delete_script called ({target_org}, {target_scope}, {target_kvm}) ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "kvm-migration-scripts", "3-delete_registry_kvms.py")
        
        # Execute script from project root
        result = subprocess.run([
            "python", script_path, 
            "--org", target_org, 
            "--scope", target_scope, 
            "--kvm", target_kvm
        ], cwd=PROJECT_ROOT)
        
        if result.returncode != 0:
            return {"status": "error", "message": "Deletion script failed."}
            
        # Locate the new log file
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "delete_kvms_run")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        
        if not list_of_files:
            return {"status": "success", "message": "Script ran, but log was missing."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_lines = f.readlines()
            
        # Extract metrics
        deleted = sum(1 for line in log_lines if "[SUCCESS]" in line)
        failed = sum(1 for line in log_lines if "[FAILURE]" in line)
        
        return {
            "status": "success", 
            "metrics": {
                "deleted": deleted,
                "failed": failed
            }
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}
    
def run_view_all_kvms_script() -> dict:
    """Executes the validation script and returns the live data directly to the agent."""
    print("--- Tool: run_view_all_kvms_script called ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "kvm-migration-scripts", "4-validate_kvms.py")
        
        # Capture the standard output (stdout) where the script prints the JSON
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT, capture_output=True, text=True)
        
        if result.returncode == 0:
            # Instead of looking for a file, we parse the JSON printed by the script
            # (We will update the script to print the final JSON to stdout)
            try:
                # Find the start of the JSON block in the output
                output = result.stdout
                json_start = output.find('{')
                json_data = json.loads(output[json_start:])
                return {"status": "success", "data": json_data}
            except:
                return {"status": "error", "message": "Failed to parse script output."}
        else:
            return {"status": "error", "message": result.stderr}
            
    except Exception as e:
        return {"status": "error", "message": str(e)}
    

def run_transform_developer_script() -> dict:
    """Executes 1-transform_developers.py and extracts the list of names."""
    print("--- Tool: run_transform_developer_script called ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "developer-migration-scripts", "1-transform_developers.py")
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        
        if result.returncode != 0:
            return {"status": "error", "message": "Script failed."}
            
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "transform_developers_run")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        if not list_of_files:
            return {"status": "success", "message": "No log generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_lines = f.readlines()
            
        # Parse names for the client-facing UI
        success_names = [line.split(": ")[1].strip() for line in log_lines if "[SUCCESS]" in line]
        failure_names = [line.split(": ")[1].strip() for line in log_lines if "[FAILURE]" in line]
        
        return {
            "status": "success", 
            "metrics": {
                "total_success": len(success_names),
                "total_failed": len(failure_names)
            },
            "transformed_developers": success_names,
            "failed_developers": failure_names
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}
    
def run_import_developer_script() -> dict:
    """Executes 2-import_developers.py and returns metrics."""
    try:
        script_path = os.path.join(PROJECT_ROOT, "developer-migration-scripts", "2-import_developers.py")
        subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "import_developers_run")
        latest_file = max(glob.glob(os.path.join(log_dir, "*.log")), key=os.path.getctime)
        with open(latest_file, 'r') as f: lines = f.readlines()
        
        successes = [l.split(": ")[1].strip() for l in lines if "[SUCCESS]" in l]
        return {"status": "success", "metrics": {"imported": len(successes)}, "imported_names": successes}
    except Exception as e: return {"status": "error", "message": str(e)}

def run_delete_developer_script(target_org: str, target_developer: str) -> dict:
    """Executes 3-delete_developers.py with specific target parameters and returns metrics."""
    print(f"--- Tool: run_delete_developer_script called ({target_org}, {target_developer}) ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "developer-migration-scripts", "3-delete_developers.py")
        
        # Execute script with arguments
        result = subprocess.run([
            "python", script_path, 
            "--org", target_org, 
            "--developer", target_developer
        ], cwd=PROJECT_ROOT, capture_output=True, text=True)
        
        # Parse the structured JSON output directly from stdout
        output = result.stdout
        marker = "---AGENT_STRUCTURED_OUTPUT---"
        
        if marker in output:
            json_str = output.split(marker)[-1].strip()
            stats = json.loads(json_str)
            return {"status": "success", "metrics": stats}
            
        if result.returncode != 0:
            return {"status": "error", "message": "Deletion script failed.", "details": result.stderr}
            
        return {"status": "error", "message": "Script ran, but structured output was missing."}
        
    except Exception as e:
        return {"status": "error", "message": str(e)}
    
# ==============================================================================
# KVM & DEVELOPER IMPORT TOOLS (SHIELDED)
# ==============================================================================
    
def run_import_script() -> dict:
    """Executes 2-import_kvm.py and returns metrics."""
    try:
        script_path = os.path.join(PROJECT_ROOT, "kvm-migration-scripts", "2-import_kvm.py")
        subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "import_kvms_run")
        latest_file = max(glob.glob(os.path.join(log_dir, "*.log")), key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f: content = f.read()
        
        import re
        def get_stat(label):
            match = re.search(rf"{label}\s*:\s*(\d+)", content)
            return int(match.group(1)) if match else 0

        stats = {
            "maps_created": get_stat("Maps Created"),
            "maps_synced": get_stat("Maps Synced"),
            "entries_created": get_stat("Entries Created"),
            "entries_updated": get_stat("Entries Updated"),
            "failures": get_stat("Failures")
        }
        return {"status": "success", "metrics": stats}
    except Exception as e: return {"status": "error", "message": str(e)}


def run_view_all_developers_script() -> dict:
    """Executes the live validation script and returns live developer data from Apigee."""
    print("--- Tool: run_view_all_developers_script called ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "developer-migration-scripts", "4-view_developers.py")
        
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT, capture_output=True, text=True)
        
        if result.returncode == 0:
            try:
                output = result.stdout
                json_start = output.find('{')
                json_data = json.loads(output[json_start:])
                
                # Truncate the list of developers to save LLM context window
                if "live_developers" in json_data and isinstance(json_data["live_developers"], list):
                    total = len(json_data["live_developers"])
                    json_data["live_developers"] = json_data["live_developers"][:15]
                    json_data["note"] = f"Showing 15 of {total} live developers."
                    
                return {"status": "success", "data": json_data}
            except:
                return {"status": "error", "message": "Failed to parse script output."}
        else:
            return {"status": "error", "message": result.stderr[-500:]}
            
    except Exception as e:
        return {"status": "error", "message": str(e)[:500]}
    
def run_transform_api_product_script() -> dict:
    """Executes api_product_transformation.py and parses the log for metrics."""
    print("--- Tool: run_transform_api_product_script called ---")
    try:
        script_path = os.path.join(PROJECT_ROOT, "product-migration-scripts", "1-api_product_transformation.py")
        
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        
        if result.returncode != 0:
            return {"status": "error", "message": "Script failed to execute properly."}
            
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "transform_api_products")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        
        if not list_of_files:
            return {"status": "success", "message": "Script ran, but no log file was generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_lines = f.readlines()
            
        success_count = sum(1 for line in log_lines if "* Cleaned & Transformed:" in line)
        error_count = sum(1 for line in log_lines if "⚠️ Error processing" in line)
        
        return {
            "status": "success", 
            "metrics": {
                "successfully_transformed": success_count,
                "errors_encountered": error_count
            }
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}


def run_import_api_product_script(human_proxy_confirmation: bool) -> dict:
    """Executes 2-import_api_product.py. Requires the agent to confirm the user said yes."""
    print(f"--- Tool: run_import_api_product_script called (Confirmed: {human_proxy_confirmation}) ---")
    
    if not human_proxy_confirmation:
        return {"status": "aborted", "message": "Human user did not confirm proxy existence. Aborting import."}
        
    try:
        script_path = os.path.join(PROJECT_ROOT, "product-migration-scripts", "2-import_api_product.py")
        
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT, text=True)
        
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "import_api_products_run")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        
        if not list_of_files:
            return {"status": "error", "message": "Script ran but no log file was generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_lines = f.readlines()
            log_content = "".join(log_lines)
            
        import re
        def extract_stat(label):
            match = re.search(rf"{label}\s*:\s*(\d+)", log_content)
            return int(match.group(1)) if match else 0

        stats = {
            "files_processed": extract_stat("Files Processed"),
            "products_created": extract_stat("Products Created"),
            "skipped_missing_proxies": extract_stat("Skipped Missing Proxies"),
            "files_deleted": extract_stat("Files Deleted"),
            "failures": extract_stat("Failures")
        }

        # --- NEW: Extract specific warnings and errors ---
        skipped_details = []
        error_details = []
        current_product = "Unknown"

        for line in log_lines:
            if "📌 Product:" in line:
                current_product = line.split("Product:")[1].strip()
            elif "⚠️ Skipping due to missing proxies" in line:
                reason = line.split("⚠️")[-1].strip()
                skipped_details.append(f"Product: {current_product}\n   ⚠️ {reason}")
            elif "❌ Failed to create" in line:
                reason = line.split("❌")[-1].strip()
                error_details.append(f"Product: {current_product}\n   ❌ {reason}")

        return {
            "status": "success", 
            "metrics": stats,
            "skipped_details": skipped_details,
            "error_details": error_details
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}


def run_delete_api_product_script(human_deletion_confirmation: bool) -> dict:
    """Executes 3-delete_all_api_product.py, automatically passing 'YES' to the destructive action prompt."""
    print(f"--- Tool: run_delete_api_product_script called (Confirmed: {human_deletion_confirmation}) ---")
    
    if not human_deletion_confirmation:
        return {"status": "aborted", "message": "Human user did not confirm deletion. Aborting."}
        
    try:
        script_path = os.path.join(PROJECT_ROOT, "product-migration-scripts", "3-delete_all_api_product.py")
        
        # We pass 'YES\n' to stdin to bypass the interactive destructive warning prompt
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT, input="YES\n", text=True)
        
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "delete_api_products_run")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        
        if not list_of_files:
            return {"status": "error", "message": "Script ran but no log file was generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_content = f.read()
            
        def extract_stat(label):
            match = re.search(rf"{label}\s*:\s*(\d+)", log_content)
            return int(match.group(1)) if match else 0

        stats = {
            "products_deleted": extract_stat("Products Deleted"),
            "skipped_in_use": extract_stat("Skipped In Use"),
            "already_missing": extract_stat("Already Missing"),
            "failures": extract_stat("Failures")
        }

        return {"status": "success", "metrics": stats}
        
    except Exception as e:
        return {"status": "error", "message": str(e)}
    
def scan_local_product_proxies() -> dict:
    """Scans transformed API Product JSON files to extract a list of required API proxies."""
    print("--- Tool: scan_local_product_proxies called ---")
    try:
        if PROJECT_ROOT not in sys.path:
            sys.path.append(PROJECT_ROOT)
        import config
        
        output_dir = getattr(config, 'OUTPUT_DIR', 'transformed_resources')
        product_dir = os.path.join(PROJECT_ROOT, output_dir, "org", "apiproducts")
        
        if not os.path.exists(product_dir):
            return {"status": "error", "message": f"Directory not found: {product_dir}. Have you transformed the products yet?"}
            
        product_files = glob.glob(os.path.join(product_dir, "*.json"))
        if not product_files:
            return {"status": "success", "proxies": [], "message": "No API Product files found."}
            
        all_proxies = set()
        for file_path in product_files:
            with open(file_path, 'r', encoding='utf-8') as f:
                try:
                    data = json.load(f)
                    all_proxies.update(data.get("proxies", []))
                except json.JSONDecodeError:
                    pass
                    
        return {
            "status": "success", 
            "proxies": sorted(list(all_proxies)),
            "count": len(all_proxies)
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

def run_transform_app_script() -> dict:
    """Executes 1-app_transformation.py and parses the log for metrics."""
    print("--- Tool: run_transform_app_script called ---")
    try:
        # Assumes PROJECT_ROOT is defined at the top of execution_tools.py
        script_path = os.path.join(PROJECT_ROOT, "apps-migration-script", "1-app_transformation.py")
        
        if not os.path.exists(script_path):
            return {"status": "error", "message": f"Script not found at: {script_path}"}
            
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT)
        
        if result.returncode != 0:
            return {"status": "error", "message": "Script failed to execute properly."}
            
        # Search for the generated log file (handles slight variations in folder names)
        log_search_pattern = os.path.join(PROJECT_ROOT, "run_logs", "*app*transform*", "*.log")
        list_of_files = glob.glob(log_search_pattern)
        
        # Fallback if standard folder isn't found
        if not list_of_files:
            list_of_files = glob.glob(os.path.join(PROJECT_ROOT, "run_logs", "*app*", "*.log"))
            
        if not list_of_files:
            return {"status": "success", "message": "Script ran successfully, but no log file was generated to extract metrics."}
            
        # Parse the latest log file for success and error markers
        latest_file = max(list_of_files, key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_lines = f.readlines()
            
        # UPDATED: Match the exact emojis and text output by 1-app_transformation.py
        success_count = sum(1 for line in log_lines if "✅ Transformed:" in line)
        error_count = sum(1 for line in log_lines if "❌ FAILED:" in line or "❌ CRITICAL ERROR" in line)
        
        return {
            "status": "success", 
            "metrics": {
                "successfully_transformed": success_count,
                "errors_encountered": error_count
            }
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}


def run_import_app_script(human_dependency_confirmation: bool) -> dict:
    """Executes 2-import_apps.py. Requires the agent to confirm the user gave the green light."""
    print(f"--- Tool: run_import_app_script called (Confirmed: {human_dependency_confirmation}) ---")
    
    # The Safety Lock (Enforced by the Agent)
    if not human_dependency_confirmation:
        return {"status": "aborted", "message": "Human user did not confirm dependencies. Aborting import."}
        
    try:
        # Assumes PROJECT_ROOT is defined at the top of execution_tools.py
        script_path = os.path.join(PROJECT_ROOT, "apps-migration-script", "2-import_apps.py")
        
        if not os.path.exists(script_path):
            return {"status": "error", "message": f"Script not found at: {script_path}"}
        
        # Execution (No input injection needed since we removed the prompt from the script)
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT, text=True)
        
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "import_apps_run")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        
        if not list_of_files:
            return {"status": "error", "message": "Script ran but no log file was generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_lines = f.readlines()
            log_content = "".join(log_lines)
            
        import re
        def extract_stat(label):
            match = re.search(rf"{label}\s*:\s*(\d+)", log_content)
            return int(match.group(1)) if match else 0

        stats = {
            "files_processed": extract_stat("Files Processed"),
            "apps_created": extract_stat("Apps Created"),
            "files_deleted": extract_stat("Files Deleted"),
            "failures": extract_stat("Failures")
        }

        # Extract specific warnings and errors to pass back to the LLM
        error_details = []
        current_app = "Unknown"

        for line in log_lines:
            if "📌 App:" in line:
                current_app = line.split("App:")[1].strip()
            elif "❌" in line:
                reason = line.split("❌")[-1].strip()
                # If the error line doesn't already specify the file, give it context
                if "Skipping" not in line and "processing" not in line:
                    error_details.append(f"App: {current_app}\n   ❌ {reason}")
                else:
                    error_details.append(f"❌ {reason}")

        return {
            "status": "success", 
            "metrics": stats,
            "error_details": error_details
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}

def validate_local_app_dependencies() -> dict:
    """Scans local transformed App JSON files to extract required Developers and API Products."""
    print("--- Tool: validate_local_app_dependencies called ---")
    try:
        if PROJECT_ROOT not in sys.path:
            sys.path.append(PROJECT_ROOT)
        import config
        
        output_dir = getattr(config, 'OUTPUT_DIR', 'transformed_resources')
        app_dir = os.path.join(PROJECT_ROOT, output_dir, "org", "apps_transformed")
        
        if not os.path.exists(app_dir):
            return {"status": "error", "message": f"Directory not found: {app_dir}. Have you transformed the apps yet?"}
            
        app_files = glob.glob(os.path.join(app_dir, "*.json"))
        if not app_files:
            return {"status": "success", "developers": [], "api_products": [], "message": "No App files found."}
            
        all_devs = set()
        all_products = set()
        
        for file_path in app_files:
            with open(file_path, 'r', encoding='utf-8') as f:
                try:
                    data = json.load(f)
                    
                    # Extract developer
                    if data.get("developerEmail"):
                        all_devs.add(data.get("developerEmail"))
                    
                    # Method 1: Extract API Products from root level (Your current JSON format)
                    for prod in data.get("apiProducts", []):
                        if isinstance(prod, dict) and prod.get("apiproduct"):
                            all_products.add(prod.get("apiproduct"))
                        elif isinstance(prod, str):
                            all_products.add(prod)

                    # Method 2: Extract API Products nested inside credentials (Standard Apigee format fallback)
                    for cred in data.get("credentials", []):
                        for prod in cred.get("apiProducts", []):
                            if isinstance(prod, dict) and prod.get("apiproduct"):
                                all_products.add(prod.get("apiproduct"))
                            elif isinstance(prod, str):
                                all_products.add(prod)
                                
                except json.JSONDecodeError:
                    pass
                    
        return {
            "status": "success", 
            "required_developers": sorted(list(all_devs)),
            "required_products": sorted(list(all_products)),
            "app_count": len(app_files)
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

def validate_live_app_dependencies(org: str, auth_type: str) -> dict:
    """Authenticates and compares local app dependencies against the live Apigee environment."""
    print(f"--- Tool: validate_live_app_dependencies called for org: {org} ---")
    try:
        # 1. Get local requirements first
        local_reqs = validate_local_app_dependencies()
        if local_reqs.get("status") == "error":
            return local_reqs
            
        req_devs = set(local_reqs.get("required_developers", []))
        req_prods = set(local_reqs.get("required_products", []))
        
        if not req_devs and not req_prods:
            return {"status": "success", "message": "No dependencies required."}

        # 2. Authenticate
        import config
        if auth_type.lower() == "service account":
            sa_key = os.path.join(PROJECT_ROOT, getattr(config, 'SA_KEY_DIR', ''), getattr(config, 'SA_KEY_FILE', ''))
            print(f"Authenticating via Service Account: {getattr(config, 'SA_KEY_FILE', '')}")
            subprocess.run(["gcloud", "auth", "activate-service-account", "--key-file", sa_key, "--quiet"], check=True)
        else:
            print("Triggering browser login...")
            subprocess.run(["gcloud", "auth", "login"], check=True)
            
        token_proc = subprocess.run(["gcloud", "auth", "print-access-token"], capture_output=True, text=True, check=True)
        token = token_proc.stdout.strip()

        # 3. Fetch Live Developers
        dev_proc = subprocess.run(["apigeecli", "developers", "list", "-o", org, "-t", token, "--disable-check"], capture_output=True, text=True)
        live_devs = set()
        if dev_proc.returncode == 0:
            try:
                dev_data = json.loads(dev_proc.stdout)
                live_devs = {d.get("email") for d in dev_data.get("developer", []) if d.get("email")}
            except: pass
            
        # 4. Fetch Live Products
        prod_proc = subprocess.run(["apigeecli", "products", "list", "-o", org, "-t", token, "--disable-check"], capture_output=True, text=True)
        live_prods = set()
        if prod_proc.returncode == 0:
            try:
                prod_data = json.loads(prod_proc.stdout)
                live_prods = {p.get("name") for p in prod_data.get("apiProduct", []) if p.get("name")}
            except: pass

        # 5. Compare
        missing_devs = req_devs - live_devs
        missing_prods = req_prods - live_prods
        
        return {
            "status": "success",
            "missing_developers": list(missing_devs),
            "missing_products": list(missing_prods),
            "ready_to_import": len(missing_devs) == 0 and len(missing_prods) == 0
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

def run_cleanup_credentials_script(human_cleanup_confirmation: bool) -> dict:
    """Executes cleanup_duplicate_credentials.py to remove empty auto-generated keys. Requires human confirmation."""
    print(f"--- Tool: run_cleanup_credentials_script called (Confirmed: {human_cleanup_confirmation}) ---")
    
    # Safety Lock
    if not human_cleanup_confirmation:
        return {"status": "aborted", "message": "User declined credential cleanup."}
        
    try:
        # Assumes PROJECT_ROOT is defined at the top of execution_tools.py
        script_path = os.path.join(PROJECT_ROOT, "apps-migration-script", "3-cleanup_duplicate_credentials.py")
        
        if not os.path.exists(script_path):
            return {"status": "error", "message": f"Script not found at: {script_path}"}
        
        # Execute the script
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT, text=True)
        
        # Locate the log file
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "cleanup_credentials_run")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        
        if not list_of_files:
            return {"status": "error", "message": "Script ran but no log file was generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_content = f.read()
            
        import re
        def extract_stat(label):
            match = re.search(rf"{label}\s*:\s*(\d+)", log_content)
            return int(match.group(1)) if match else 0

        # Parse the summary stats
        stats = {
            "apps_scanned": extract_stat("Apps Scanned"),
            "apps_needing_cleanup": extract_stat("Apps Needing Cleanup"),
            "keys_deleted": extract_stat("Keys Deleted"),
            "failures": extract_stat("Failures")
        }

        return {
            "status": "success", 
            "metrics": stats
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}

def run_delete_app_script(human_deletion_confirmation: bool) -> dict:
    """Executes delete_apps.py to remove apps based on the local registry. Requires human confirmation."""
    print(f"--- Tool: run_delete_app_script called (Confirmed: {human_deletion_confirmation}) ---")
    
    # Safety Lock
    if not human_deletion_confirmation:
        return {"status": "aborted", "message": "User did not confirm the destructive deletion. Aborting."}
        
    try:
        script_path = os.path.join(PROJECT_ROOT, "apps-migration-script", "4-delete_all_apps.py")
        
        if not os.path.exists(script_path):
            return {"status": "error", "message": f"Script not found at: {script_path}"}
        
        # We pass 'YES\n' to stdin to bypass the interactive destructive warning prompt
        result = subprocess.run(["python", script_path], cwd=PROJECT_ROOT, input="YES\n", text=True)
        
        log_dir = os.path.join(PROJECT_ROOT, "run_logs", "delete_apps_run")
        list_of_files = glob.glob(os.path.join(log_dir, "*.log"))
        
        if not list_of_files:
            return {"status": "error", "message": "Script ran but no log file was generated."}
            
        latest_file = max(list_of_files, key=os.path.getctime)
        with open(latest_file, 'r', encoding='utf-8') as f:
            log_content = f.read()
            
        import re
        def extract_stat(label):
            match = re.search(rf"{label}\s*:\s*(\d+)", log_content)
            return int(match.group(1)) if match else 0

        # Parse the summary stats generated by the script
        stats = {
            "apps_deleted": extract_stat("Apps Deleted"),
            "failures": extract_stat("Failures"),
            "already_missing": extract_stat("Already Missing")
        }

        return {"status": "success", "metrics": stats}
        
    except Exception as e:
        return {"status": "error", "message": str(e)}